server:
  port: 8081

spring:
  application:
    name: DevT Spring Boot - Liquibase demo
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibasedb
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml